apiVersion: apps/v1

kind: Deployment

metadata:
  name: laguinho-github
  labels:
    app: laguinho-github
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laguinho-github
  
  template:
    metadata:
      name: laguinho-github
      labels:
        app: laguinho-github

    spec:
      containers:
      - name: laguinho-github
        image: docker.pkg.github.com/joserenan/laguinho-github/laguinho-github:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred