apiVersion: v1

kind: Service

metadata:
  name: laguinho-api

spec:
  selector:
    app: laguinho-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
  clusterIP: 10.96.97.251